### ISSUE TITLE
关于生成隐写文本中的sample和threshold采样

### ISSUE THREAD

**Issue by forsuixinsuoyu** [YangzlTHU/Linguistic-Steganography-and-Steganalysis#1]
作者您好！请问sample和threshold方法生成的样本，是如何隐藏信息的呢？
因为在huffman编码信息并采用topk采样的情况下，可以根据秘密信息选取对应的生成样点，但是sample和threshold的生成是按概率抽样，那么就没法按照秘密信息选择相应的生成样点了，比较好奇这种情况是如何嵌入秘密信息的🙇‍

此外，也想向您请教一下arithmetic编码映射秘密信息的时候，如何控制嵌入率？也就是得到数据中不同的bit/word。

非常期待您的解答！感谢！😊

**Comment by YangzlTHU** [comment]
具体您指的哪段代码呢？

**Comment by YangzlTHU** [comment]
> 作者您好！请问sample和threshold方法生成的样本，是如何隐藏信息的呢？
> 因为在huffman编码信息并采用topk采样的情况下，可以根据秘密信息选取对应的生成样点，但是sample和threshold的生成是按概率抽样，那么就没法按照秘密信息选择相应的生成样点了，比较好奇这种情况是如何嵌入秘密信息的🙇‍
> 
> 此外，也想向您请教一下arithmetic编码映射秘密信息的时候，如何控制嵌入率？也就是得到数据中不同的bit/word。
> 
> 非常期待您的解答！感谢！😊

您指的是哪一段代码呢？

**Comment by forsuixinsuoyu** [comment]
> > 作者您好！请问sample和threshold方法生成的样本，是如何隐藏信息的呢？
> > 因为在huffman编码信息并采用topk采样的情况下，可以根据秘密信息选取对应的生成样点，但是sample和threshold的生成是按概率抽样，那么就没法按照秘密信息选择相应的生成样点了，比较好奇这种情况是如何嵌入秘密信息的🙇‍
> > 此外，也想向您请教一下arithmetic编码映射秘密信息的时候，如何控制嵌入率？也就是得到数据中不同的bit/word。
> > 非常期待您的解答！感谢！😊
> 
> 您指的是哪一段代码呢？

您好！主要是在这个仓库看到了您上传的一些隐写文本数据，里面有“arthmetic-sample-1bit.txt”、“arthmetic-sample-2bit.txt”类似的样例，所以有以上一些疑问，比较好奇是怎样生成的。另外，我主要是阅读了您的《vae_stega》这篇论文找到这里来的，感谢！

**Comment by YangzlTHU** [comment]
> > > 作者您好！请问sample和threshold方法生成的样本，是如何隐藏信息的呢？
> > > 因为在huffman编码信息并采用topk采样的情况下，可以根据秘密信息选取对应的生成样点，但是sample和threshold的生成是按概率抽样，那么就没法按照秘密信息选择相应的生成样点了，比较好奇这种情况是如何嵌入秘密信息的🙇‍
> > > 此外，也想向您请教一下arithmetic编码映射秘密信息的时候，如何控制嵌入率？也就是得到数据中不同的bit/word。
> > > 非常期待您的解答！感谢！😊
> > 
> > 
> > 您指的是哪一段代码呢？
> 
> 您好！主要是在这个仓库看到了您上传的一些隐写文本数据，里面有“arthmetic-sample-1bit.txt”、“arthmetic-sample-2bit.txt”类似的样例，所以有以上一些疑问，比较好奇是怎样生成的。另外，我主要是阅读了您的《vae_stega》这篇论文找到这里来的，感谢！

哦哦好的，感谢您关注我们的工作。

其实sample和threshold方法我们写在另一篇文章里，目前好像还没公布出来，还在审稿中。算是个trick吧。后续接收后我们会把这部分隐写代码也共享出来。

再次感谢您对我们工作的关注。后续如果您对这方面依然感兴趣，我们可以随时邮件保持联系。

**Comment by forsuixinsuoyu** [comment]
> > > > 作者您好！请问sample和threshold方法生成的样本，是如何隐藏信息的呢？
> > > > 因为在huffman编码信息并采用topk采样的情况下，可以根据秘密信息选取对应的生成样点，但是sample和threshold的生成是按概率抽样，那么就没法按照秘密信息选择相应的生成样点了，比较好奇这种情况是如何嵌入秘密信息的🙇‍
> > > > 此外，也想向您请教一下arithmetic编码映射秘密信息的时候，如何控制嵌入率？也就是得到数据中不同的bit/word。
> > > > 非常期待您的解答！感谢！😊
> > > 
> > > 
> > > 您指的是哪一段代码呢？
> > 
> > 
> > 您好！主要是在这个仓库看到了您上传的一些隐写文本数据，里面有“arthmetic-sample-1bit.txt”、“arthmetic-sample-2bit.txt”类似的样例，所以有以上一些疑问，比较好奇是怎样生成的。另外，我主要是阅读了您的《vae_stega》这篇论文找到这里来的，感谢！
> 
> 哦哦好的，感谢您关注我们的工作。
> 
> 其实sample和threshold方法我们写在另一篇文章里，目前好像还没公布出来，还在审稿中。算是个trick吧。后续接收后我们会把这部分隐写代码也共享出来。
> 
> 再次感谢您对我们工作的关注。后续如果您对这方面依然感兴趣，我们可以随时邮件保持联系。

好的，明白了，感谢您的回复！期待你们的后续工作！
